/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SimpleCMPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  contactsFolder: "Contacts",
  dashboardPath: "Contact Dashboard.md",
  dashboardEngine: "dataview",
  basePath: "Contacts.base"
};
var PRIORITIES = ["high", "medium", "low"];
var PRIORITY_LABELS = {
  high: "High (7\u201314 days)",
  medium: "Medium (30 days)",
  low: "Low (60\u201390 days)"
};
var RELATIONSHIPS = [
  "client",
  "colleague",
  "friend",
  "lead",
  "mentor",
  "acquaintance",
  "other"
];
var CADENCE_DAYS = [7, 14, 30, 60, 90];
function today() {
  return (0, import_obsidian.moment)().format("YYYY-MM-DD");
}
function addDays(days) {
  return (0, import_obsidian.moment)().add(days, "days").format("YYYY-MM-DD");
}
function sanitizeFileName(name) {
  return name.replace(/[\\/:*?"<>|#^[\]]/g, "-").trim();
}
async function ensureFolder(app, folderPath) {
  if (!app.vault.getAbstractFileByPath(folderPath)) {
    await app.vault.createFolder(folderPath);
  }
}
var NewContactModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.data = {
      name: "",
      email: "",
      phone: "",
      company: "",
      priority: "medium",
      relationship: "acquaintance",
      followupDays: 30
    };
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    this.titleEl.setText("New contact");
    new import_obsidian.Setting(contentEl).setName("Full name").addText((text) => {
      text.setPlaceholder("Jane Smith").onChange((v) => this.data.name = v);
      text.inputEl.focus();
    });
    new import_obsidian.Setting(contentEl).setName("Email").addText(
      (text) => text.setPlaceholder("jane@example.com").onChange((v) => this.data.email = v.trim())
    );
    new import_obsidian.Setting(contentEl).setName("Phone").addText(
      (text) => text.setPlaceholder("555-1234").onChange((v) => this.data.phone = v.trim())
    );
    new import_obsidian.Setting(contentEl).setName("Company").addText(
      (text) => text.setPlaceholder("Acme Corp").onChange((v) => this.data.company = v.trim())
    );
    new import_obsidian.Setting(contentEl).setName("Priority").addDropdown((dd) => {
      PRIORITIES.forEach((p) => dd.addOption(p, PRIORITY_LABELS[p]));
      dd.setValue(this.data.priority).onChange(
        (v) => this.data.priority = v
      );
    });
    new import_obsidian.Setting(contentEl).setName("Relationship").addDropdown((dd) => {
      RELATIONSHIPS.forEach((r) => dd.addOption(r, r));
      dd.setValue(this.data.relationship).onChange(
        (v) => this.data.relationship = v
      );
    });
    new import_obsidian.Setting(contentEl).setName("Follow-up cadence").addDropdown((dd) => {
      CADENCE_DAYS.forEach((d) => dd.addOption(String(d), `Every ${d} days`));
      dd.setValue(String(this.data.followupDays)).onChange(
        (v) => this.data.followupDays = Number(v)
      );
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close())).addButton(
      (btn) => btn.setButtonText("Create contact").setCta().onClick(() => this.submit())
    );
    contentEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && e.target instanceof HTMLInputElement) {
        e.preventDefault();
        this.submit();
      }
    });
  }
  submit() {
    this.data.name = this.data.name.trim();
    if (!this.data.name) {
      new import_obsidian.Notice("Name is required.");
      return;
    }
    this.onSubmit(this.data);
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ContactSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, contacts, onChoose) {
    super(app);
    this.contacts = contacts;
    this.onChoose = onChoose;
    this.setPlaceholder("Search contacts\u2026");
  }
  getItems() {
    return this.contacts;
  }
  getItemText(file) {
    return file.basename;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
};
var InteractionNoteModal = class extends import_obsidian.Modal {
  constructor(app, contact, onSubmit) {
    super(app);
    this.note = "";
    this.contact = contact;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    this.titleEl.setText(`Log interaction \u2014 ${this.contact.basename}`);
    new import_obsidian.Setting(contentEl).setName("Interaction note").addText((text) => {
      text.setPlaceholder("e.g. Called re: contract renewal").onChange((v) => this.note = v);
      text.inputEl.focus();
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          this.submit();
        }
      });
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close())).addButton(
      (btn) => btn.setButtonText("Log interaction").setCta().onClick(() => this.submit())
    );
  }
  submit() {
    const note = this.note.trim();
    if (!note) {
      new import_obsidian.Notice("Please enter an interaction note.");
      return;
    }
    this.onSubmit(note);
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var SimpleCMSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    var _a, _b;
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Contacts folder").setDesc(
      "Folder where new contact notes are created and where the dashboard looks for contacts. If you change this after creating the dashboard, delete the dashboard note and reopen it to regenerate its queries."
    ).addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.contactsFolder).setValue(this.plugin.settings.contactsFolder).onChange(async (value) => {
        this.plugin.settings.contactsFolder = value.trim() || DEFAULT_SETTINGS.contactsFolder;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Dashboard note path").setDesc(
      "Path to your Contact Dashboard note, relative to the vault root."
    ).addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.dashboardPath).setValue(this.plugin.settings.dashboardPath).onChange(async (value) => {
        this.plugin.settings.dashboardPath = value.trim() || DEFAULT_SETTINGS.dashboardPath;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Dashboard engine").setDesc(
      "Dataview keeps the classic tables. Bases (beta) generates a reusable Contacts.base with saved views (Overdue, Due Today, Next 7/30 Days, All) and embeds it \u2014 lighter on mobile. After changing this, delete the dashboard note and re-open it to regenerate."
    ).addDropdown(
      (dd) => dd.addOption("dataview", "Dataview (classic tables)").addOption("bases", "Bases (saved views, beta)").setValue(this.plugin.settings.dashboardEngine).onChange(async (value) => {
        this.plugin.settings.dashboardEngine = value === "bases" ? "bases" : "dataview";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Base file path").setDesc(
      "Path of the generated base file, used when the engine is Bases."
    ).addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.basePath).setValue(this.plugin.settings.basePath).onChange(async (value) => {
        this.plugin.settings.basePath = value.trim() || DEFAULT_SETTINGS.basePath;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Actions").setHeading();
    new import_obsidian.Setting(containerEl).setName("Open contact dashboard").setDesc("Open the dashboard note in the current pane.").addButton(
      (btn) => btn.setButtonText("Open dashboard").onClick(async () => {
        await this.plugin.openDashboard();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Restore default paths").setDesc("Reset all folder paths back to the defaults.").addButton(
      (btn) => btn.setButtonText("Restore defaults").setWarning().onClick(async () => {
        this.plugin.settings = { ...DEFAULT_SETTINGS };
        await this.plugin.saveSettings();
        this.display();
        new import_obsidian.Notice("Paths restored to defaults.");
      })
    );
    new import_obsidian.Setting(containerEl).setName("Dependency status").setHeading();
    const dvInstalled = (_b = (_a = this.app.plugins) == null ? void 0 : _a.enabledPlugins) == null ? void 0 : _b.has(
      "dataview"
    );
    if (dvInstalled) {
      containerEl.createEl("p", {
        text: "\u2705 Dataview is installed and enabled."
      });
    } else {
      const warning = containerEl.createDiv({ cls: "scm-dataview-warning" });
      warning.createEl("strong", { text: "\u26A0\uFE0F Dataview is not enabled." });
      warning.createEl("p", {
        text: "The Contact Dashboard requires the Dataview community plugin. Please install and enable it from Settings \u2192 Community Plugins."
      });
    }
  }
};
var SimpleCMPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SimpleCMSettingTab(this.app, this));
    this.addCommand({
      id: "new-contact",
      name: "New contact",
      callback: () => this.createContact()
    });
    this.addCommand({
      id: "log-interaction",
      name: "Log contact interaction",
      callback: () => this.logInteraction()
    });
    this.addCommand({
      id: "open-dashboard",
      name: "Open contact dashboard",
      callback: () => this.openDashboard()
    });
    this.addRibbonIcon("contact", "Simple Contact Manager", () => {
      this.openDashboard();
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ── Create Contact ──────────────────────────────────────────────────────
  createContact() {
    new NewContactModal(this.app, async (data) => {
      await this.writeContactNote(data);
    }).open();
  }
  async writeContactNote(data) {
    const todayStr = today();
    const nextFollowup = addDays(data.followupDays);
    const folderPath = this.settings.contactsFolder;
    const fileName = sanitizeFileName(data.name);
    const filePath = `${folderPath}/${fileName}.md`;
    const existing = this.app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian.TFile) {
      new import_obsidian.Notice(`\u26A0\uFE0F A contact named "${fileName}" already exists.`);
      await this.app.workspace.getLeaf().openFile(existing);
      return;
    }
    await ensureFolder(this.app, folderPath);
    const body = [
      `# ${data.name}`,
      "",
      "## Contact Info",
      `- **Email:** ${data.email}`,
      `- **Phone:** ${data.phone}`,
      `- **Company:** ${data.company}`,
      "",
      "## Notes",
      "",
      "",
      "## Interaction Log",
      "",
      `### ${todayStr}`,
      "- Contact created",
      ""
    ].join("\n");
    const newFile = await this.app.vault.create(filePath, body);
    await this.app.fileManager.processFrontMatter(newFile, (fm) => {
      fm.type = "contact";
      fm.status = "active";
      fm.name = data.name;
      fm.email = data.email;
      fm.phone = data.phone;
      fm.tags = ["contact"];
      fm.created = todayStr;
      fm.updated = todayStr;
      fm.contact = {
        company: data.company,
        priority: data.priority,
        relationship: data.relationship,
        last_contacted: todayStr,
        followup_days: data.followupDays,
        next_followup: nextFollowup
      };
    });
    await this.app.workspace.getLeaf().openFile(newFile);
    new import_obsidian.Notice(
      `\u2705 Created contact: ${data.name} \u2014 next follow-up in ${data.followupDays} days (${nextFollowup})`
    );
  }
  // ── Log Interaction ─────────────────────────────────────────────────────
  logInteraction() {
    const contactFiles = this.getContactFiles();
    if (contactFiles.length === 0) {
      new import_obsidian.Notice(
        "No contacts found. Create a contact first using the 'New contact' command."
      );
      return;
    }
    new ContactSuggestModal(this.app, contactFiles, (file) => {
      new InteractionNoteModal(this.app, file, async (noteText) => {
        await this.writeInteractionLog(file, noteText);
      }).open();
    }).open();
  }
  async writeInteractionLog(file, noteText) {
    var _a, _b, _c;
    const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const followupDays = Number((_c = (_b = fm == null ? void 0 : fm.contact) == null ? void 0 : _b.followup_days) != null ? _c : fm == null ? void 0 : fm.followup_days) || 30;
    const todayStr = today();
    const nextFollowup = addDays(followupDays);
    await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      const contact = frontmatter.contact && typeof frontmatter.contact === "object" ? frontmatter.contact : frontmatter.contact = {};
      contact.last_contacted = todayStr;
      contact.next_followup = nextFollowup;
      frontmatter.updated = todayStr;
      for (const k of [
        "last_contacted",
        "next_followup",
        "followup_days",
        "priority",
        "relationship",
        "company"
      ]) {
        if (k in frontmatter && !(k in contact))
          contact[k] = frontmatter[k];
        delete frontmatter[k];
      }
    });
    await this.app.vault.process(file, (content) => {
      const logHeading = /^## Interaction Log$/m;
      const todayHeading = `### ${todayStr}`;
      if (!logHeading.test(content)) {
        return `${content.trimEnd()}

## Interaction Log

${todayHeading}
- ${noteText}
`;
      }
      const todayAtTop = new RegExp(
        `^## Interaction Log\\n+${todayHeading}$`,
        "m"
      );
      if (todayAtTop.test(content)) {
        return content.replace(todayAtTop, (match) => `${match}
- ${noteText}`);
      }
      return content.replace(
        logHeading,
        (match) => `${match}

${todayHeading}
- ${noteText}
`
      );
    });
    new import_obsidian.Notice(
      `\u2705 Logged interaction for ${file.basename} \u2014 next follow-up: ${nextFollowup}`
    );
  }
  // ── Open Dashboard ──────────────────────────────────────────────────────
  async openDashboard() {
    const dashPath = this.settings.dashboardPath;
    let file = this.app.vault.getAbstractFileByPath(dashPath);
    if (!(file instanceof import_obsidian.TFile)) {
      file = await this.createDashboard(dashPath);
      if (!file)
        return;
    }
    await this.app.workspace.getLeaf().openFile(file);
  }
  async createDashboard(dashPath) {
    if (this.settings.dashboardEngine === "bases") {
      return this.createDashboardBases(dashPath);
    }
    const folder = this.settings.contactsFolder;
    const content = [
      "# \u{1F4C7} Contact Dashboard",
      "",
      "> [!tip] This dashboard is powered by the Simple Contact Manager plugin and Dataview.",
      "> Each section auto-updates when you open this note.",
      "",
      "---",
      "",
      "## \u{1F534} Overdue \u2014 Reach Out Now",
      "",
      "```dataview",
      "TABLE WITHOUT ID",
      `  ("[[" + file.name + "|" + name + "]]") AS "Contact",`,
      '  email AS "Email",',
      '  contact.priority AS "Priority",',
      '  contact.last_contacted AS "Last Contacted",',
      '  contact.next_followup AS "Was Due"',
      `FROM "${folder}"`,
      "WHERE contact.next_followup < date(today) AND is_template != true",
      "SORT contact.priority DESC, contact.next_followup ASC",
      "```",
      "",
      "---",
      "",
      "## \u{1F7E1} Due Today",
      "",
      "```dataview",
      "TABLE WITHOUT ID",
      `  ("[[" + file.name + "|" + name + "]]") AS "Contact",`,
      '  email AS "Email",',
      '  contact.priority AS "Priority",',
      '  contact.last_contacted AS "Last Contacted"',
      `FROM "${folder}"`,
      "WHERE contact.next_followup = date(today) AND is_template != true",
      "SORT contact.priority DESC",
      "```",
      "",
      "---",
      "",
      "## \u{1F7E2} Upcoming \u2014 Next 7 Days",
      "",
      "```dataview",
      "TABLE WITHOUT ID",
      `  ("[[" + file.name + "|" + name + "]]") AS "Contact",`,
      '  email AS "Email",',
      '  contact.priority AS "Priority",',
      '  contact.next_followup AS "Follow-up Date",',
      '  (contact.next_followup - date(today)).days + " days" AS "In"',
      `FROM "${folder}"`,
      "WHERE contact.next_followup > date(today) AND contact.next_followup <= date(today) + dur(7 days) AND is_template != true",
      "SORT contact.next_followup ASC",
      "```",
      "",
      "---",
      "",
      "## \u{1F4C5} Upcoming \u2014 Next 30 Days",
      "",
      "```dataview",
      "TABLE WITHOUT ID",
      `  ("[[" + file.name + "|" + name + "]]") AS "Contact",`,
      '  email AS "Email",',
      '  contact.priority AS "Priority",',
      '  contact.next_followup AS "Follow-up Date",',
      '  (contact.next_followup - date(today)).days + " days" AS "In"',
      `FROM "${folder}"`,
      "WHERE contact.next_followup > date(today) + dur(7 days) AND contact.next_followup <= date(today) + dur(30 days) AND is_template != true",
      "SORT contact.next_followup ASC",
      "```",
      "",
      "---",
      "",
      "## \u{1F5C2}\uFE0F All Contacts",
      "",
      "```dataview",
      "TABLE WITHOUT ID",
      `  ("[[" + file.name + "|" + name + "]]") AS "Name",`,
      '  email AS "Email",',
      '  contact.company AS "Company",',
      '  contact.priority AS "Priority",',
      '  contact.relationship AS "Type",',
      '  contact.last_contacted AS "Last Contacted",',
      '  contact.next_followup AS "Next Follow-up",',
      '  contact.followup_days AS "Cadence (days)"',
      `FROM "${folder}"`,
      "WHERE is_template != true",
      "SORT contact.priority DESC, name ASC",
      "```"
    ].join("\n");
    try {
      const parentFolder = dashPath.split("/").slice(0, -1).join("/");
      if (parentFolder) {
        await ensureFolder(this.app, parentFolder);
      }
      return await this.app.vault.create(dashPath, content);
    } catch (e) {
      new import_obsidian.Notice(
        `Could not create dashboard at "${dashPath}". Check the path in plugin settings.`
      );
      return null;
    }
  }
  // ── Bases dashboard (Workstream B) ───────────────────────────────────────
  /** One reusable base with saved views, replacing the five near-duplicate
   * Dataview tables. Nested contact.* keys are dot-accessible; date() forces
   * date typing on the nested values. Kept in sync with Contacts.base. */
  buildContactsBase() {
    return `filters:
  and:
    - file.hasTag("contact")
    - 'note.is_template != true'
formulas:
  last_contact_age: 'today() - date(contact.last_contacted)'
  due_in: 'date(contact.next_followup) - today()'
properties:
  file.name:
    displayName: Contact
  contact.priority:
    displayName: Priority
  contact.relationship:
    displayName: Type
  contact.company:
    displayName: Company
  contact.last_contacted:
    displayName: Last Contacted
  contact.next_followup:
    displayName: Next Follow-up
  contact.followup_days:
    displayName: Cadence (days)
  formula.last_contact_age:
    displayName: Last Contact Age
  formula.due_in:
    displayName: In
views:
  - type: table
    name: Overdue
    filters:
      and:
        - 'date(contact.next_followup) < today()'
    order: [file.name, contact.priority, contact.last_contacted, contact.next_followup, formula.last_contact_age]
    sort:
      - property: contact.priority
        direction: DESC
      - property: contact.next_followup
        direction: ASC
  - type: table
    name: Due Today
    filters:
      and:
        - 'date(contact.next_followup) == today()'
    order: [file.name, contact.priority, contact.last_contacted]
    sort:
      - property: contact.priority
        direction: DESC
  - type: table
    name: Next 7 Days
    filters:
      and:
        - 'date(contact.next_followup) > today()'
        - 'date(contact.next_followup) <= today() + "7 days"'
    order: [file.name, contact.priority, contact.next_followup, formula.due_in]
    sort:
      - property: contact.next_followup
        direction: ASC
  - type: table
    name: Next 30 Days
    filters:
      and:
        - 'date(contact.next_followup) > today() + "7 days"'
        - 'date(contact.next_followup) <= today() + "30 days"'
    order: [file.name, contact.priority, contact.next_followup, formula.due_in]
    sort:
      - property: contact.next_followup
        direction: ASC
  - type: table
    name: All Contacts
    order: [file.name, contact.company, contact.priority, contact.relationship, contact.last_contacted, contact.next_followup, contact.followup_days]
    sort:
      - property: contact.priority
        direction: DESC
      - property: file.name
        direction: ASC
`;
  }
  /** Create/refresh the base file, then a thin dashboard note that embeds it. */
  async createDashboardBases(dashPath) {
    const basePath = this.settings.basePath || DEFAULT_SETTINGS.basePath;
    try {
      const existingBase = this.app.vault.getAbstractFileByPath(basePath);
      if (existingBase instanceof import_obsidian.TFile) {
        await this.app.vault.modify(existingBase, this.buildContactsBase());
      } else {
        const baseParent = basePath.split("/").slice(0, -1).join("/");
        if (baseParent)
          await ensureFolder(this.app, baseParent);
        await this.app.vault.create(basePath, this.buildContactsBase());
      }
      const baseName = basePath.replace(/\.base$/, "");
      const content = [
        "# \u{1F4C7} Contact Dashboard",
        "",
        "> [!tip] Powered by Simple Contact Manager and Obsidian Bases.",
        "> Tap a view tab (Overdue \xB7 Due Today \xB7 Next 7 Days \xB7 Next 30 Days \xB7 All)",
        "> to switch. Auto-updates as contacts change.",
        "",
        `![[${baseName}.base]]`,
        ""
      ].join("\n");
      const parentFolder = dashPath.split("/").slice(0, -1).join("/");
      if (parentFolder)
        await ensureFolder(this.app, parentFolder);
      return await this.app.vault.create(dashPath, content);
    } catch (e) {
      new import_obsidian.Notice(
        `Could not create Bases dashboard. Check the dashboard and base paths in plugin settings.`
      );
      return null;
    }
  }
  // ── Utility ─────────────────────────────────────────────────────────────
  getContactFiles() {
    const folder = this.settings.contactsFolder;
    return this.app.vault.getMarkdownFiles().filter((f) => {
      var _a, _b;
      if (!f.path.startsWith(folder + "/"))
        return false;
      const cache = this.app.metadataCache.getFileCache(f);
      if (!cache)
        return false;
      const tags = (_a = (0, import_obsidian.getAllTags)(cache)) != null ? _a : [];
      return tags.includes("#contact") && ((_b = cache.frontmatter) == null ? void 0 : _b.is_template) !== true;
    });
  }
};
